# Site settings
title: tamatojuice
author: Tam T. Dang
email: tamdang@tamatojuice.com
description: "hey there, you little badass."
baseurl: ""
url: "http://www.tamatojuice.com"
github_username: teedang19
twitter_username: tamatojuiice

# Build settings
markdown: kramdown
permalink: pretty
